version: "3.8"

services:
  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  product-catalog-service:
    build: ./product-catalog-service
    env_file: ./product-catalog-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  shopping-cart-service:
    build: ./shopping-cart-service
    env_file: ./shopping-cart-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - product-catalog-service
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    env_file: ./order-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - user-service
      - product-catalog-service
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    env_file: ./payment-service/.env
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

volumes:
  mongodb_data:

networks:
  ecommerce-network:
    driver: bridge
